### ISSUE TITLE
mentor_introduction 페이지 기본 요소, 스타일 구성

### ISSUE THREAD

**Issue by VirtualExplorer7613** [osamhack2021/web_Guntor-Guntee_EarlyFried#10]
## 💡 이슈 요약 
mentor_introduction 페이지 기본 요소, 스타일 구성을 진행한다.
## 📃 이슈 본문
![_mentor_introduction_ 페이지](https://user-images.githubusercontent.com/37505713/135097290-8d9bc4fd-6126-44be-bf54-9775760db087.png)
figma를 참고하여 페이지 기본 요소, 스타일을 작성한다.

##  📌 체크 리스트
- [x] mentor_introduction 기본 내용과 스타일 구성

**Comment by nonaninona** [comment]
mentoring page하고 연결했어!

**Comment by VirtualExplorer7613** [comment]
고마워!😀

2021년 10월 1일 (금) 오후 11:02, nonaninona ***@***.***>님이 작성:
