### ISSUE TITLE
커스텀 유저 모델(user) 장고 시스템에 등록

### ISSUE THREAD

**Issue by Yanghyeondong** [osamhack2021/web_Guntor-Guntee_EarlyFried#2]
## 💡 이슈 요약 
`django` 내부 앱 중 `users` (커스텀 유저)모델을 장고 시스템의 유저 모델로 등록
## 📃 이슈 본문
군토&군티 서비스를 위한 커스텀 유저 모델인  `users` 를 장고 시스템의 유저 모델로 등록해 활용할 수 있도록 설정.
user ERD 구조 참고
![image](https://user-images.githubusercontent.com/37038105/134795511-7a79797e-639a-43ab-9350-1c9356d0dd25.png)

##  📌 체크 리스트
- [x] `python manage.py createsuperuser` 명령어를 통해 생성된 모델 확인하기

**Comment by chaejunlee** [comment]
config/settings.py에 AUTH_USER_MODEL 추가하면서 완료했습니다.
