### ISSUE TITLE
back: Permission 설정

### ISSUE THREAD

**Issue by nagi0101** [osamhack2021/web_Guntor-Guntee_EarlyFried#28]
## 💡 이슈 요약 
각 기능별로 permission을 설정한다.
## 📃 이슈 본문
현재 permission이 설정되어 있지 않아 Root URL에서도 권한을 요구하는 일이 발생하고 있다.
적절한 권한 설정을 통해 해당 문제를 해결해야 한다.
##  📌 체크 리스트
- [ ] Permission 설정을 통해 보안이 필요하지 않은 데이터에는 로그인 필요하지 않게 하기
- [ ] Permission 설정을 통해 보안이 필요한 데이터에는 로그인 필요하게 하기

**Comment by Yanghyeondong** [comment]
퍼미션 설정에서 각 파일마다 다음과 같이 permission.py 를 만들고 개별 퍼미션 세부사항을 적용해 주면 좀 더 자세한 수정이 가능할 것 같습니다
ex. user 에 대한 예시

```
from rest_framework import permissions


class IsOwnerOrReadOnly(permissions.BasePermission):

    def has_object_permission(self, request, view, obj):
        if request.method in permissions.SAFE_METHODS:
            return True
        return obj == request
```
유저 view에서 다음과 같이 적용
```
permission_classes = [IsOwnerOrReadOnly]
```

**Comment by Yanghyeondong** [comment]
일단 전체 권한을 IsAuthenticatedOrReadOnly 로 주었으나, 추후 수정이 가능할것 같아 계속 열어두겠습니다
