### ISSUE TITLE
front : mentoring 페이지에 쓰이는 서브 메뉴바 개발

### ISSUE THREAD

**Issue by nonaninona** [osamhack2021/web_Guntor-Guntee_EarlyFried#3]
## 💡 이슈 요약 
mentoring 페이지에 존재하는 mentoring_5 기능 개발

## 📃 이슈 본문
![image](https://user-images.githubusercontent.com/53222283/134794586-59345393-bb6b-4d03-9f9a-551454de9434.png)
위의 사진과 같은 서브 메뉴바 개발

#### 핵심 기능
* 같은 페이지의 특정 스크롤 위치로 바로 가기
* 항상 화면 상단에 위치
* 클릭 시 하이라이팅 기능

다른 페이지들에도 같은 기능이 있기 때문에 추후 컴포넌트화 고려

##  📌 체크 리스트
- [x] 기본 내용과 스타일 작성
- [x] 바로가기 기능 추가
- [x] 항시 화면 상단 위치 기능 추가
- [x] 클릭 시 하이라이팅 기능 추가

**Comment by chaejunlee** [comment]
수고 많습니다~! :100: :100: :100:

**Comment by nonaninona** [comment]
> 수고 많습니다~! 💯 💯 💯

고마워용
