### ISSUE TITLE
back: 시간대 한국으로 설정

### ISSUE THREAD

**Issue by nagi0101** [osamhack2021/web_Guntor-Guntee_EarlyFried#37]
## 💡 이슈 요약 
Django의 시스템 시간값을 한국 시간대로 수정해야 한다.
## 📃 이슈 본문
현재 Django의 시간값이 기본 설정으로 되어있어 한국의 시간값을 저장하지 못하고 있다.
시간값 수정이 필요하다. 
##  📌 체크 리스트
- [x] Django 시간값 한국 시간대로 수정

**Comment by Yanghyeondong** [comment]
![image](https://user-images.githubusercontent.com/37038105/135856984-b3ecdda7-a3a7-4eac-ae41-efbab092c9ec.png)
위와 같이 한국 시간값이 정상으로 들어감을 확인했습니다
