### ISSUE TITLE
back: SpecificationCard에 ImageField 추가

### ISSUE THREAD

**Issue by nagi0101** [osamhack2021/web_Guntor-Guntee_EarlyFried#38]
## 💡 이슈 요약 
SpecificationCard 모델에 ImageField 추가
## 📃 이슈 본문
현재 SpecificationCard모델에는 ImageField가 없다.
프론트엔드상에서는 이미지를 띄우기로 했으므로 이를 수정해야 한다.
##  📌 체크 리스트
- [x] SpecificationCard Model 수정
- [x] SpecificationCard Serializer 수정
- [x] SpecificationCard  API Docs 수정

**Comment by Yanghyeondong** [comment]
이미지 필드 수정이 성공적으로 완료되었습니다!
