### ISSUE TITLE
back: Media file serving 설정

### ISSUE THREAD

**Issue by nagi0101** [osamhack2021/web_Guntor-Guntee_EarlyFried#39]
## 💡 이슈 요약 
Media file serving이 가능하도록 Django 설정을 해야한다.
## 📃 이슈 본문
현재의 Django 설정으로는 Image 등의 Media file을 서빙하지 못한다.
이를 수정하여 정상적인 작동을 하도록 해야한다.
##  📌 체크 리스트
- [ ] Media file serving 설정

**Comment by Yanghyeondong** [comment]
![image](https://user-images.githubusercontent.com/37038105/135867250-064adf55-d783-49d5-8cec-8f3dbd808d15.png)
![image](https://user-images.githubusercontent.com/37038105/135867294-ec393234-1940-4fc9-9a21-f7360b6738fc.png)
위와 같이 이미지 받는것을 확인했습니다.
다만, 확실히 작동하는지는 다른 분의 검증이 필요할것 같아 아직 이슈를 닫지 않겠습니다
