### ISSUE TITLE
CustomUser 생성을 위한 User Manager 생성

### ISSUE THREAD

**Issue by chaejunlee** [osamhack2021/web_Guntor-Guntee_EarlyFried#4]
## 💡 이슈 요약 

`CustomUser` 생성을 위한 `User Manager`을 모델에 추가.

## 📃 이슈 본문

커스텀 유저 모델(user) 장고 시스템에 등록 #2 를 통해 등록한 CustomUser를 추가할 수 있는
`BaseUserManager`를 'User' 모델에 추가

##  📌 체크 리스트
- [x] `BaseUserManager` 추가하기
- [x] `createsuperuser` 제대로 작동하는지 확인

**Comment by chaejunlee** [comment]
잉 이거 자동으로 close 안되넵?

**Comment by chaejunlee** [comment]
tags 앱의 Tag model에 대해 `makemigration`과 `migrate`가 되지 않습니다. 벌써 migration에 대한 충돌이 생긴 것 같습니다. `develop`에서 migration 파일 수정이 필요해 보입니다.
@Yanghyeondong @nagi0101

**Comment by nagi0101** [comment]
> tags 앱의 Tag model에 대해 `makemigration`과 `migrate`가 되지 않습니다. 벌써 migration에 대한 충돌이 생긴 것 같습니다. `develop`에서 migration 파일 수정이 필요해 보입니다.
> @Yanghyeondong @nagi0101 

저녁에 마이그래이션 파일 재생성하겠습니다
