### ISSUE TITLE
serializers, viewset 추가 및 router 수정

### ISSUE THREAD

**Issue by Yanghyeondong** [osamhack2021/web_Guntor-Guntee_EarlyFried#5]
## 💡 이슈 요약 

django 내부 커스텀 앱들에 대한 serializer , viewset 추가 및 url router 수정.

## 📃 이슈 본문

users, tags, questions, portfolio, mentoring 앱들에 대해 `serializer.py`, `url.py`를 생성하여 serializer 및 router 기능을 추가한다.
또한 `viewset` 을 통해 기본적인 CRUD를 구성한다

##  📌 체크 리스트
- [x] serializer 추가 및 정리
- [x] viewset 추가 및 정리
- [x] url router 수정 및 정리

**Comment by Yanghyeondong** [comment]
[[update]: urls, views 의 serializers 연동 업데이트 및 테스트](https://github.com/osamhack2021/web_Guntor-Guntee_EarlyFried/commit/ea26e77e4565f748a509720661e4105ac21a4005) 
3개의 앱에 대해서 시리얼라이저 및 뷰셋 기본 적용이 완료되었습니다. 
다만, 추후 나머지 앱들과 같이 다시 정리할 필요가 있습니다.

**Comment by nagi0101** [comment]
[[update]: router 수정](https://github.com/osamhack2021/web_Guntor-Guntee_EarlyFried/commit/21499f4ae0561aa2829c5b07b84087df08f7583e)
router를 수정하여 API Root에서 모든 모델들에 대해 접근이 가능한 URL이 뜨도록 만들었습니다. 모든 체크리스트의 항목들을 마쳤으니, 해당 이슈는 닫도록 하겠습니다.

**Comment by chaejunlee** [comment]
수고 많았어용~!
